// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyP5Uocgiu7ZsC9RHOG67Gg3pFryZOx2s',
    appId: '1:901417429740:web:a7b72c99f25cc56cac93c9',
    messagingSenderId: '901417429740',
    projectId: 'rede-social-flutter-7aeed',
    authDomain: 'rede-social-flutter-7aeed.firebaseapp.com',
    storageBucket: 'rede-social-flutter-7aeed.firebasestorage.app',
    measurementId: 'G-T7GHCBX91H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqB9wupwn-1oC1yVod0F3TavVED3FIYo',
    appId: '1:901417429740:android:8987631a211e6313ac93c9',
    messagingSenderId: '901417429740',
    projectId: 'rede-social-flutter-7aeed',
    storageBucket: 'rede-social-flutter-7aeed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2mzPw5FGpO7GG_vO4mIf7O0IJFZUuLqo',
    appId: '1:901417429740:ios:e294be8ab4dee77bac93c9',
    messagingSenderId: '901417429740',
    projectId: 'rede-social-flutter-7aeed',
    storageBucket: 'rede-social-flutter-7aeed.firebasestorage.app',
    iosBundleId: 'com.example.redeSocialFlutter',
  );
}
